WhatsNews/WhatsNews/Models/Category.cs
namespace WhatsNews.Models;

public class Category
{
    public int Id { get; set; }
    public string Name { get; set; }
    
    public ICollection<Article>? Articles { get; set; }
}

WhatsNews/WhatsNews/Areas/Admin/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using WhatsNews.Data.Interfaces;
using WhatsNews.Models;

namespace WhatsNews.Areas.Admin.Controllers;

[Area("Admin")]
public class CategoriesController : Controller
{
    private readonly ICategoryRepository _context;

    public CategoriesController(ICategoryRepository context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        var categories = _context.GetCategories();
        return View(categories);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Category category)
    {
        if (!ModelState.IsValid) return View();

        if (_context.Create(category))
        {
            return RedirectToAction("index");
        }

        return View();
    }

    public IActionResult Edit(int id)
    {
        var category = _context.GetCategoryById(id);
        return View(category);
    }

    [HttpPost]
    public IActionResult Edit(Category category)
    {
        if (!ModelState.IsValid) return View(category);
        
        _context.Update(category);
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        var category = _context.GetCategoryById(id);
        return View(category);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult DeleteConfirmed(int id)
    {
        var category = _context.GetCategoryById(id);
        if (category == null)
            return RedirectToAction("index");
        _context.Delete(category);
        return RedirectToAction("index");
    }
}

WhatsNews/WhatsNews/Controllers/ArticlesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.Internal;
using WhatsNews.Data.Interfaces;
using WhatsNews.ViewModels;

namespace WhatsNews.Controllers;

public class ArticlesController : Controller
{
    private readonly IArticleRepository _articleRepository;
    private readonly ICommentRepository _commentRepository;

    public ArticlesController(IArticleRepository articleRepository, ICommentRepository commentRepository)
    {
        _articleRepository = articleRepository;
        _commentRepository = commentRepository;
    }

    [HttpGet]
    [Route("/article/{id}")]
    public IActionResult Show(int id)
    {
        var article = _articleRepository.GetById(id);
        if (article == null)
            return NotFound();

        var comments = _commentRepository.GetByPostId(id);
        
        var articleComment = new ArticleCommentViewModel()
        {
            Id = article.Id,
            Category = article.Category,
            Content = article.Content,
            Index1 = article.Index1,
            Index2 = article.Index2,
            Index3 = article.Index3,
            Likes = article.Likes,
            Title = article.Title,
            AType = article.AType,
            ImagePath = article.ImagePath,
            PublishDate = article.PublishDate,
            ShortDescription = article.ShortDescription,
            Views = article.Views,
            Comments = comments
        };

        
        return View(articleComment);
    }

}

WhatsNews/WhatsNews/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using WhatsNews.Data.Interfaces;

namespace WhatsNews.Controllers;

public class CategoriesController : Controller
{
    private readonly ICategoryRepository _categoryRepository;
    private readonly IArticleRepository _articleRepository;

    public CategoriesController(ICategoryRepository categoryRepository, IArticleRepository articleRepository)
    {
        _categoryRepository = categoryRepository;
        _articleRepository = articleRepository;
    }

    public async Task<IActionResult> CategoryArticles(int categoryId)
    {
        var category = _categoryRepository.GetCategoryById(categoryId);
        var articles = _articleRepository.GetByCategory(category);
        return View(articles);
    }
}

WhatsNews/WhatsNews/ViewComponents/ArticlesTypeReportViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WhatsNews.Data.Interfaces;
using WhatsNews.Models.Enum;

namespace WhatsNews.ViewComponents;

public class ArticlesTypeReportViewComponent : ViewComponent
{
    private readonly IArticleRepository _context;

    public ArticlesTypeReportViewComponent(IArticleRepository context)
    {
        _context = context;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var articless = await _context.GetByTypeAsync(AType.Report);
        return View(articless);
    }
}

WhatsNews/WhatsNews/ViewComponents/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WhatsNews.Data.Interfaces;

namespace WhatsNews.ViewComponents;

public class CategoriesViewComponent : ViewComponent
{
    private readonly ICategoryRepository _categoryRepository;

    public CategoriesViewComponent(ICategoryRepository categoryRepository)
    {
        _categoryRepository = categoryRepository;
    }

    public async Task<IViewComponentResult> InvokeAsync(int count = 10)
    {
        var categories = await _categoryRepository.GetCategoriesAsync(count);
        return View(categories);
    }
}

WhatsNews/WhatsNews/Views/Categories/CategoryArticles.cshtml
@using System.Runtime.InteropServices
@model IEnumerable<Article>

@{
    ViewBag.Title = "category";
    Layout = "_Layout";
}

<div class="latest-posts">
    <div class="container-fluid">
        <div class="col-md-9">
            <div class="blog-title-span">
                <span class="title">اخبار و مقالات</span>
            </div>
            
            @foreach(var item in @Model)
            {
            
                <div class="col-md-4">
                    <div class="post-box">
                        <a asp-controller="Articles" asp-action="Show" asp-route-id="@item.Id">
                            <figure>
                                <img src="@item.ImagePath" alt="">
                                <figcaption class="meta-fig">
                                    <span><i class="fa fa-clock-o"></i> @item.PublishDate.Date</span>&nbsp;
                                    <span><i class="fa fa-comment-o"></i> 12</span>
                                </figcaption>
                                @* <figcaption class="view"> *@
                                @*     <span>بخش ویژه</span> *@
                                @*     <span>انجمن</span> *@
                                @*     <span>اتاق خبر</span> *@
                                @* </figcaption> *@
                            </figure>
                            <div class="text-p">
                                <h5>@item.Title</h5>
                                <p>@item.ShortDescription</p>
                                <div class="text-rigt">
                                    <a asp-controller="Articles" asp-action="Show" asp-route-id="@item.Id">ادامه ...</a>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            }
        </div>
        <div class="col-md-3 main-content">
            <!-- categories -->
            @await Component.InvokeAsync("Categories")
            
            <!-- report articles -->
            @await Component.InvokeAsync("ArticlesTypeReport")
            
        </div>
        <div class="col-md-12 text-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item"><a class="page-link" href="#">قبلی</a></li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">بعدی</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>