WhatsNews_DjangoVersion/WhatsNews/News/urls.py
from django.conf.urls.static import static
from django.urls import path
import News.views as views
from WhatsNews.settings import MEDIA_ROOT, MEDIA_URL, DEBUG


app_name = 'News'


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('article/<int:pk>/', views.SingleArticleView.as_view(), name='single'),
    path('news/', views.AllArticlesView.as_view(), name='all'),
    path('category/<int:pk>/', views.CategoryArticlesView.as_view(), name='category'),
    path('add_comment/', views.add_comment, name='add_comment'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact_us/', views.about_us, name='contact_us'),
    path('search/', views.search, name='search'),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

handler404 = 'News.views.handler404'

WhatsNews_DjangoVersion/WhatsNews/WhatsNews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('News.urls', namespace='News')),
]

handler404 = 'News.views.handler404'

WhatsNews_DjangoVersion/WhatsNews/News/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'category'
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'tag'
        verbose_name = 'tag'
        verbose_name_plural = 'tags'

    def __str__(self):
        return self.name


class Article(models.Model):
    types = [
        ('N', 'Normal'),
        ('P', 'Picture'),
        ('V', 'Video'),
        ('R', 'Report'),
        ('I', 'Interview'),
    ]

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='article_images/')
    content = models.TextField()
    short_description = models.CharField(max_length=150, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    like_count = models.IntegerField(default=0)
    view_count = models.IntegerField(default=0)
    first_level_index = models.BooleanField(default=False)
    second_level_index = models.BooleanField(default=False)
    third_level_index = models.BooleanField(default=False)
    type = models.CharField(max_length=1, choices=types, default='N')
    tags = models.ManyToManyField(Tag)

    class Meta:
        db_table = 'article'
        verbose_name = 'article'
        verbose_name_plural = 'articles'

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Article, related_name='comments', on_delete=models.CASCADE, blank=True, null=True)
    auther_name = models.CharField(max_length=100, blank=True, null=True)
    auther_email = models.EmailField(blank=True, null=True)
    comment = models.TextField(null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)

WhatsNews_DjangoVersion/WhatsNews/News/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic.list import ListView
from django.views.generic import DetailView
from .Data.repository import CategoryRepository, ArticleRepository, TagRepository, CommentRepository
from django.http import JsonResponse
# search part
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity




class IndexView(View):
    template_name = 'index.html'
    def get(self, request):
        indexed_articles = ArticleRepository.get_indexed_articles(request)
        categories = CategoryRepository.get_all_with_post_count(request)
        recent_articles = ArticleRepository.get_recent_articles(request)
        most_viewed_article = ArticleRepository.get_most_viewed_articles(request)
        second_indexed_article = ArticleRepository.get_second_indexed_article(request)
        third_indexed_article = ArticleRepository.get_third_indexed_article(request)

        # عکس یادداشت گزارش گفتگو
        pictural_articles = ArticleRepository.get_articles_in_type(request, 'P')
        interview_articles = ArticleRepository.get_articles_in_type(request, 'I')  # گزارش
        report_articles = ArticleRepository.get_articles_in_type(request, 'R')  # یادداشت
        conversation_articles = ArticleRepository.get_articles_in_type(request, 'C')  # گفتگو

        context = {
            'indexed_articles': indexed_articles,
            'most_viewed_article': most_viewed_article,
            'second_indexed_article': second_indexed_article,
            'third_indexed_article': third_indexed_article,
            'categories': categories,
            'recent_articles': recent_articles,
            'pictural_articles': pictural_articles,
            'interview_articles': interview_articles,
            'report_articles': report_articles,
            'conversation_articles': conversation_articles,
        }
        return render(request, self.template_name, context)


class SingleArticleView(DetailView):
    context_object_name = 'post'
    template_name = 'single.html'

    def get_object(self, queryset=None):
        id_ = self.kwargs.get('pk')
        post = ArticleRepository.get_by_id(self.request, id_)
        post.view_count += 1
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id_ = self.kwargs.get('pk')
        post = ArticleRepository.get_by_id(self.request, id_)
        comments = CommentRepository.get_by_post(self.request, post)
        context['comments'] = comments
        return context


class AllArticlesView(ListView):
    context_object_name = 'articles'
    template_name = 'blog.html'
    paginate_by = 16

    def get_queryset(self):
        return ArticleRepository.get_all(self.request)


class CategoryArticlesView(ListView):
    template_name = 'category.html'
    context_object_name = 'articles'
    paginate_by = 9

    def get_queryset(self):
        id_ = self.kwargs.get('pk')
        category = CategoryRepository.get_by_id(self.request, id_)
        return ArticleRepository.get_by_category(self.request, category)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id_ = self.kwargs.get('pk')
        category = CategoryRepository.get_by_id(self.request, id_)
        categories = CategoryRepository.get_all_with_post_count(self.request)
        recent_articles = ArticleRepository.get_recent_articles(self.request)
        context['category_name'] = category.name
        context['categories'] = categories
        context['recent_articles'] = recent_articles
        return context


def add_comment(request):
    # if not request.user and not request.user.is_authenticated():
        # return "You are not an admin!"

    if request.method == 'POST':
        auther_name = request.POST.get('author_name', False)
        auther_email = request.POST.get('author_email', False)
        content = request.POST.get('content', False)
        post_id = request.POST.get('post_id', False)
        if False in [auther_name, auther_email, content, post_id]:
            return JsonResponse({'error': 'Fill all the fields.'}, status=400)
        ar = ArticleRepository()
        post = ar.get_by_id(post_id)

        comment_data = {
            'auther_name': auther_name,
            'auther_email': auther_email,
            'comment': content,
            'post': post,
        }
        cr = CommentRepository()
        status = cr.create(comment_data)

        if status >= 0:
            comment = CommentRepository.get_by_id(request, status)
            return JsonResponse({
                'auther_name': comment.auther_name,
                'auther_email': comment.auther_email,
                'comment': comment.comment,
            })
        else: return JsonResponse({'error': 'Failed to create comment'}, status=400)
    else:
        print('got a post request')
        return JsonResponse({'error': 'Invalid request method'}, status=405)


def about_us(request):
    if request.method == "GET":
        return render(request, 'about-us.html')


def search(request):
    if request.method == "GET":
        articles = ArticleRepository.get_all_names(request)
        query = request.GET.get('query')

        vectorizer = TfidfVectorizer()
        tfidf_matrix = vectorizer.fit_transform(articles)
        query_vector = vectorizer.transform([query])
        similarities = cosine_similarity(query_vector, tfidf_matrix).flatten()
        ranked_indices = similarities.argsort()[::-1]

        context = {}
        for idx in ranked_indices:
            print(f"مقاله: {articles[idx]}, شباهت: {similarities[idx]:.2f}")
            context[articles[idx]] = similarities[idx]
        return JsonResponse(**context)


def handler404(request, exception):
    return render(request, 'p404.html', status=404)

WhatsNews_DjangoVersion/WhatsNews/News/templates/about-us.html
{% extends 'base/template.html' %}
{% load static %}


{% block body %}
<div class="single_post">
    <div class="container-fluid">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="post_content text-center">
                <span>درباره ما</span>
                <p>سلام. قالب سایت از سئو90 گرفته شده.</p>
                <p>بقیه پروژه های من در <a href="https://github.com/Ehsan-004" target="_blank">صفحه گیتهاب من</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

WhatsNews_DjangoVersion/WhatsNews/News/templates/blog.html
{% extends 'base/template.html' %}
{% load static %}
{% block page_title %}همه خبرها{% endblock %}

{% block body %}
<div class="latest-posts">
    <div class="container-fluid">
        <div class="blog-title-span">
            <span class="title">همه خبرها</span>
        </div>

        {% for article in articles %}
        <div class="col-md-3">
            <div class="post-box">
                <a href="{% url 'News:single' article.id %}">
                    <figure>
                        <img src="{{ article.image.url }}" alt="">
                        <figcaption class="meta-fig">
                            <span><i class="fa fa-clock-o"></i>{{ article.create_date|date }}</span>&nbsp;
                            <span><i class="fa fa-comment-o"></i> 12</span>
                        </figcaption>
                        <figcaption class="view">
                            {% for tag in article.tags.all %}
                            <span>{{ tag.name }}</span>
                            {% endfor %}
                        </figcaption>
                    </figure>
                    <div class="text-p">
                        <h5>{{ article.title }}</h5>
                        <p>{{ article.short_description }}</p>
                        <div class="text-rigt">
                            <a href="{% url 'News:single' article.id %}">ادامه ...</a></div>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}

        <div class="col-md-12 text-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">&laquo; اولین</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                    {% endif %}
{#                    <span class="current page-item">{{ page_obj.number }} از {{ page_obj.paginator.num_pages }}. </span>#}
                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item"><span class="page-itme">{{ i }}</span></li>
                        {% else %}
                            <li class="page-itme"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">آخرین &raquo;</a></li>
                    {% endif %}

                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

WhatsNews_DjangoVersion/WhatsNews/News/templates/category.html
{% extends 'base/template.html' %}
{% load static %}

{% block page_title %}خبرها در دسته {{ category_name }}{% endblock %}

{% block body %}
<div class="latest-posts">
    <div class="container-fluid">
        <div class="col-md-9">
            <div class="blog-title-span">
                <span class="title">اخبار {{ category_name }}</span>
            </div>

            {% for article in articles %}
            <div class="col-md-4">
                <div class="post-box">
                    <a href="{% url 'News:single' article.id %}">
                        <figure>
                            <img src="{{ article.image.url }}" alt="">
                            <figcaption class="meta-fig">
                                <span><i class="fa fa-clock-o"></i>{{ article.create_date|date }}</span>&nbsp;
                                <span><i class="fa fa-comment-o"></i> 12</span>
                            </figcaption>
                            <figcaption class="view">
                                {% for tag in article.tags.all %}
                                <span>{{ tag }}</span>
                                {% endfor %}
                            </figcaption>
                        </figure>
                        <div class="text-p">
                            <h5>{{ article.title }}</h5>
                            <p>{{ article.content }}</p>
                            <div class="text-rigt">
                                <a href="{% url 'News:single' article.id %}">ادامه ...</a></div>
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="col-md-3 main-content">
            <div class="l-sidebar">
                <div class="cat-sidebar">
                    <span class="title">دسته بندی مطالب</span>
                    <div class="text-left"><i class="fa fa-folder-o"></i></div>
                    <ul>
                        {% for category in categories %}
                        <li><a href="{% url 'News:category' category.id %}">{{ category.name }}</a><span>{{ category.post_count }}</span></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="l-sidebar">
                <div class="cat-sidebar report">
                    <span class="title">تازه ترین خبرها</span>
                    <div class="text-left"><i class="fa fa-arrows-alt"></i></div>
                    <ul>
                        {% for article in recent_articles %}
                        <li><a href="{% url 'News:single' article.id %}">{{ article.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-12 text-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">&laquo; اولین</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                    {% endif %}
{#                    <span class="current page-item">{{ page_obj.number }} از {{ page_obj.paginator.num_pages }}. </span>#}
                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item"><span class="page-itme">{{ i }}</span></li>
                        {% else %}
                            <li class="page-itme"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">آخرین &raquo;</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

WhatsNews_DjangoVersion/WhatsNews/News/templates/p404.html
{% extends 'base/template.html' %}
{% load static %}

{% block body %}
<div class="single_post">
    <div class="container-fluid">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="post_content not_found text-center">
                <span>404</span>
                <p>محتوای مورد نظر پیدا نشد !</p>
                asdlfjkas;lkdfj;alskdjfaskdjflkasdjflaksdjf;ldsakj
            </div>
        </div>
    </div>
</div>
{% endblock %}

WhatsNews_DjangoVersion/WhatsNews/News/templates/single.html
{% extends 'base/template.html' %}
{% load static %}

{% block page_title %}{{ post.title }}{% endblock %}

{% block body %}
    <div class="single_post">
        <div class="container-fluid">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="post_img">
                            <img src="{{ post.image.url }}" alt="">
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                </div>
                <div class="posts_meta text-center">
                    <span><i class="fa fa-comment-o"></i> {{ post.comments.count }} نظر</span>
                    <a href="{% url 'News:category' post.category.id %}"><span><i class="fa fa-archive"></i>{{ post.category }}</span></a>
                    <span><i class="fa fa-calendar"></i>{{ post.create_date|date }}</span>
                </div>
                <div class="post_content">
                    <h4>{{ post.title }}</h4>
                    <p>{{ post.content }}</p>
                </div>
                <div class="comments_form">
                    <h5>دیدگاه شما </h5>
                    <form id="frm" action="{% url 'News:add_comment' %}" method="post">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="author_name" id="author_name" placeholder="نام شما" required>
                            </div>
                            <div class="col-md-6">
                                <input type="email" class="form-control"  name="author_email" id="author_email" placeholder="ایمیل" required>
                            </div>
                            <div class="col-md-12">
                                <textarea class="form-control" name="content" id="content" placeholder="نظر شما ..." required></textarea>
                            </div>
                            <input type="hidden" value="{{ post.id }}" name="post_id">
                            <div class="col-md-12">
                                <div class="text-left">
                                    <input type="submit" class="btn btn-primary" id="btn_submit" value="ثبت نظر">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>


                <div class="comments_section mt-5 comments_form">
                    <h5>نظرات کاربران</h5>
                    {% for comment in comments %}
                        <div class="comment"
                             style="margin-bottom: 30px; padding: 20px; border: 1px solid #ddd; border-radius: 5px;">
                            <strong id="comment_author_name">{{ comment.auther_name }}</strong>
                            <p id="comment_text">{{ comment.comment }}</p>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block scripts %}
    <script src="{% static 'js/jQuery.js' %}"></script>
    <script type="text/javascript">
        var frm = $('#frm');
        $(document).ready(function(){
            frm.submit(function () {
                var form_data = frm.serialize();
                $.ajax({
                    type: frm.attr('method'),
                    url: frm.attr('action'),
                    data: form_data,
                    success: function (data) {
                        var newComment = `<div class="comment" style="margin-bottom: 30px; padding: 20px; border: 1px solid #ddd; border-radius: 5px;">
                            <strong id="comment_author_name">${data.auther_name}</strong>
                            <p id="comment_text">${data.comment}</p>
                            </div>`;
                        $('.comments_section').append(newComment)
                        frm.trigger('reset');
                        var lastComment = $('.comments_section .comment').first();
                        lastComment[0].scrollIntoView({
                            behavior: 'smooth',
                            block: 'center'
                        });
                    },
                    error: function(data){
                        alert('st went wrong');
                    }
                });
                return false;
            });
        });
    </script>

{% endblock %}