WhatsNews/WhatsNews/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WhatsNews.Areas.Admin.Controllers;

[Area("Admin")]
public class HomeController : Controller
{
        [Area("Admin")]
        public IActionResult Index()
        {
                return View();
        }
}

WhatsNews/WhatsNews/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WhatsNews.Data.Interfaces;
using WhatsNews.Models;

namespace WhatsNews.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IArticleRepository _articleRepository;

    public HomeController(ILogger<HomeController> logger, IArticleRepository articleRepository)
    {
        _logger = logger;
        _articleRepository = articleRepository;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult AllArticles()
    {
        var articles = _articleRepository.GetArticles();
        return Json(articles);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

WhatsNews/WhatsNews/ViewComponents/ArticlesTypetextViewComponent.cs
using System.Net.Mime;
using Microsoft.AspNetCore.Mvc;
using WhatsNews.Data.Interfaces;
using WhatsNews.Models.Enum;

namespace WhatsNews.ViewComponents;

public class ArticlesTypetextViewComponent : ViewComponent
{
    private readonly IArticleRepository _context;

    public ArticlesTypetextViewComponent(IArticleRepository context)
    {
        _context = context;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var articles = await _context.GetByTypeAsync(AType.Report);
        return View(articles);
    }
}

WhatsNews/WhatsNews/ViewComponents/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WhatsNews.Data.Interfaces;

namespace WhatsNews.ViewComponents;

public class CategoriesViewComponent : ViewComponent
{
    private readonly ICategoryRepository _categoryRepository;

    public CategoriesViewComponent(ICategoryRepository categoryRepository)
    {
        _categoryRepository = categoryRepository;
    }

    public async Task<IViewComponentResult> InvokeAsync(int count = 10)
    {
        var categories = await _categoryRepository.GetCategoriesAsync(count);
        return View(categories);
    }
}

WhatsNews/WhatsNews/ViewComponents/Indexed1ArticlesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WhatsNews.Data.Interfaces;

namespace WhatsNews.ViewComponents;

public class Indexed1ArticlesViewComponent : ViewComponent
{
    private readonly IArticleRepository _context;

    public Indexed1ArticlesViewComponent(IArticleRepository context)
    {
        _context = context;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var articles = await _context.GetIndexed2Async();
        return View(articles);
    }
}

WhatsNews/WhatsNews/ViewComponents/RecentArticlesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WhatsNews.Data.Interfaces;

namespace WhatsNews.ViewComponents;

public class RecentArticlesViewComponent : ViewComponent
{
    private readonly IArticleRepository _articleRepository;

    public RecentArticlesViewComponent(IArticleRepository articleRepository)
    {
        _articleRepository = articleRepository;
    }

    public async Task<IViewComponentResult> InvokeAsync(int count = 8)
    {
        var articles = await _articleRepository.GetArticlesAsync(count);
        return View(articles);
    }
}

WhatsNews/WhatsNews/Views/Home/Index.cshtml
@using System.Runtime.InteropServices
@{
    ViewData["Title"] = "Home Page";
}
<div class="clear-fix"></div>
<div class="row">

    <!--  -->
    <!-- Image Articles -->
    @await Component.InvokeAsync("ArticlesTypeImage")
    <!-- Image Articles -->

    <!--  -->
    <!-- Index 1 Start -->
    @await Component.InvokeAsync("Indexed1Articles")
    <!-- Index 1 End -->

    <!--  -->
    <!-- Text Start -->
    @await Component.InvokeAsync("ArticlesTypetext")
    <!-- Text End -->
</div>

<div class="clear-fix"></div>
<div class="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <div class="r-sidebar">
                    
                    <!-- Conversation Start -->
                    <!-- گفتگو -->
                    @await Component.InvokeAsync("ArticlesTypeReport")
                    <!-- گفتگو -->
                    <!-- Conversation End -->
                        
                    <div class="ads-box">
                        <span class="title">تبلیغات</span><br>

                        <!-- Ads Start -->
                        <figure>
                            <img src="~/LocalStyles/img/unnamed.jpg" alt="">
                        </figure>
                        <figure>
                            <img src="~/LocalStyles/img/unnamed.jpg" alt="">
                        </figure>
                        <!-- Conversation End -->
                        
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="content-wrapper">
                    
                    <!-- Index 2 Start -->
                    @await Component.InvokeAsync("Indexed2Articles")
                    <!-- Index 2 End -->

                    <!-- Categories Start -->
                    @await Component.InvokeAsync("Categories", new { count=5 })
                    <!-- Categories End -->
                    
                </div>
            </div>
        </div>
    </div>
    
    <div class="clear-fix"></div>
    <div class="latest-posts">
        
        <!-- Recent Articles Start -->
        <div class="container-fluid">
            <div class="blog-title-span">
                <span class="title">آخرین مطالب</span>
            </div>
            
            
            <!-- recent articles -->
            @await Component.InvokeAsync("RecentArticles")

        </div>
        <!-- Recent Articles End -->

    </div>
</div>